### ISSUE TITLE
 RMB_data_augmentation.py

### ISSUE THREAD

**Issue by creater-zq** [JansonYuan/Pytorch-Camp#2]
test_data = RMBDataset(data_dir=test_dir, transform=valid_transform) 这一行用的valid_transform。
后面反transforms时 img = transform_invert(img_tensor, train_transform)，用train_transform是不是不对呀，也需要用valid_transfrom叭

**Comment by TingsongYu** [comment]
你说的是对的，L183确实应该用valid_transform，感谢指正，github已经修改了

**Comment by creater-zq** [comment]
于老师，您的新版深度之眼pyTorch大概什么时候出？

**Comment by TingsongYu** [comment]
> 于老师，您的新版深度之眼pyTorch大概什么时候出？

我姓余！新版暂时还没计划
