### ISSUE TITLE
 lesson-21 / loss_acc_weights_grad.py

### ISSUE THREAD

**Issue by creater-zq** [JansonYuan/Pytorch-Camp#3]
1. 在158行，因为`valid_curve.append(loss.item())`是在读取验证集的for循环的外面，所以最后的`valid_curve`列表里面只有一个损失值(最后一次读取验证集数据得到的损失）。
2. 在159行打印`loss_val`时，打印的是一个`epoch`里，每次读取`batch_size`个验证集样本，来计算`batch_size`个样本损失的均值`loss.item()`，读多少次就计算多少个均值`loss.item()`，这里读取了2次，之后将2次的均值求和得到`loss_val`，这样打印的应该不是一个`epoch`的损失均值把，应该是`loss_val/len(valid_loader）`才对吧。
3. 在163行，`np.mean(valid_curve)`只有一个数据，求均值还是最后一次读取的损失。
4. 我的观点：在158行前面加上，`loss_val_epoch=loss_val/len(valid_loader）`。之后都用loss_val_epoch。

**Comment by TingsongYu** [comment]
> https://github.com/JansonYuan/Pytorch-Camp/blob/master/hello%20pytorch/lesson/lesson-21/loss_acc_weights_grad.py#L158

对的，原来的loss统计有问题，你的建议不错，158行已经修改，多谢~
