### ISSUE TITLE
关于test_data的路径问题

### ISSUE THREAD

**Issue by epiphany97** [JansonYuan/Pytorch-Camp#9]
请问老师，为什么test_data下必须建一个为名100的文件夹，然后把图片放进100文件夹里才能进行验证，直接将验证图片放在test-data下就会出现报错呢?相关代码在哪里体现的呢？

**Comment by TingsongYu** [comment]
https://github.com/JansonYuan/Pytorch-Camp/blob/master/hello%20pytorch/lesson/lesson-06/2_train_lenet.py#L169

**Comment by yeahQing** [comment]
因为RMBDataset里面读取数据是按照文件夹路径读取的，读取到给定的data_dir后，还会再往里面读取1和100两个子文件夹。如果你不想这样做，你可以修改RMBDataset里面读取数据的方法，修改get_img_info()方法。
